In [1]:
import torch

In [2]:
import numpy as np

In [4]:
r1 = torch.rand((10,10))
y = torch.rand((10,1))

In [5]:
from sklearn.metrics import pairwise_distances
def eu_distance(feature, y):
    return pairwise_distances(feature.reshape(1, -1), y.reshape(1, -1), metric='euclidean')


def feature_distance(features, y):
    dis_mat = []
    for i in range(features.shape[1]):
        tmp = []
        for j in range(features.shape[1]):
            tmp.append(np.abs(eu_distance(features[:, i], features[:, j])))
        dis_mat.append(np.array(tmp))
    dis_mat = np.array(dis_mat)
    return dis_mat

In [8]:
feature_distance(r1, y)

(10, 10, 1, 1)

In [33]:
c = feature_distance(r1, y)
c

array([[[[0.        ]],

        [[1.2297049 ]],

        [[1.5268308 ]],

        [[0.8188607 ]],

        [[1.27854   ]],

        [[1.0933372 ]],

        [[1.0975235 ]],

        [[1.2053978 ]],

        [[1.0521612 ]],

        [[1.3552142 ]]],


       [[[1.2297049 ]],

        [[0.        ]],

        [[1.1478785 ]],

        [[1.3197575 ]],

        [[1.0890201 ]],

        [[1.122232  ]],

        [[1.157124  ]],

        [[1.312699  ]],

        [[1.3909881 ]],

        [[1.2104784 ]]],


       [[[1.5268308 ]],

        [[1.1478785 ]],

        [[0.        ]],

        [[1.4117627 ]],

        [[1.3840119 ]],

        [[1.395941  ]],

        [[1.126683  ]],

        [[1.1900944 ]],

        [[1.1731299 ]],

        [[1.1868016 ]]],


       [[[0.8188607 ]],

        [[1.3197575 ]],

        [[1.4117627 ]],

        [[0.        ]],

        [[1.3291006 ]],

        [[1.1556325 ]],

        [[1.1690428 ]],

        [[1.0521064 ]],

        [[0.8506017 ]],

        [[1.2420349

In [32]:
torch.cdist(r1.transpose(-1,0) , r1.transpose(-1,0), p=2.0, compute_mode='use_mm_for_euclid_dist_if_necessary').unsqueeze(-1).unsqueeze(-1).numpy()

array([[[[0.        ]],

        [[1.2297049 ]],

        [[1.5268308 ]],

        [[0.8188607 ]],

        [[1.27854   ]],

        [[1.093337  ]],

        [[1.0975233 ]],

        [[1.2053978 ]],

        [[1.0521613 ]],

        [[1.3552142 ]]],


       [[[1.2297049 ]],

        [[0.        ]],

        [[1.1478786 ]],

        [[1.3197575 ]],

        [[1.0890201 ]],

        [[1.122232  ]],

        [[1.1571242 ]],

        [[1.312699  ]],

        [[1.3909881 ]],

        [[1.2104783 ]]],


       [[[1.5268308 ]],

        [[1.1478786 ]],

        [[0.        ]],

        [[1.4117627 ]],

        [[1.3840119 ]],

        [[1.395941  ]],

        [[1.126683  ]],

        [[1.1900944 ]],

        [[1.1731299 ]],

        [[1.1868016 ]]],


       [[[0.8188607 ]],

        [[1.3197575 ]],

        [[1.4117627 ]],

        [[0.        ]],

        [[1.3291006 ]],

        [[1.1556326 ]],

        [[1.1690428 ]],

        [[1.0521064 ]],

        [[0.8506017 ]],

        [[1.2420349

In [23]:
pairwise_distances(r1[:,0].reshape(1, -1), r1[:,1].reshape(1, -1), metric='euclidean')

array([[1.2297049]], dtype=float32)